### PR TITLE
Switch to cross-fetch to work on node.js

### PR DESCRIPTION
**Pull request by SferaDev**
PENDING: Update Api tests to match some library changes (ie: x-requested-with -> X-Requested-With)

### CODE REVIEW

**Comment by ismay** [comment]
@SferaDev Thanks for the PR! Actually we were already using isomorphic-fetch, which also allows fetching in node. We just weren't using it properly. This will be fixed with https://github.com/dhis2/d2/pull/191. I'll close it as it's already addressed, but let me know if you have any questions or remarks!

**Comment by SferaDev** [comment]
@ismay Still the patch with isomorphic-fetch doesn't work with node. See the following error under 31.4.0:

```
Error: Failed to initialise D2 Api: No fetch implementation is available
    at new Api (/mnt/d/Workspace/UPC/Metadata-Repository-Service/node_modules/src/api/Api.js:74:19)
    at Function.getApi (/mnt/d/Workspace/UPC/Metadata-Repository-Service/node_modules/src/api/Api.js:416:26)
    at init (/mnt/d/Workspace/UPC/Metadata-Repository-Service/node_modules/src/d2.js:149:26)
```

**Comment by ismay** [comment]
Hi @SferaDev, 31.4.0 does not contain the fix, we haven't drafted the release with the fix yet. I'll take a look at it today. In the meantime you could npm install the master branch of this repo: https://github.com/d2-ci/d2, that would allow you to test before we've released.

**Comment by ismay** [comment]
Published in 31.5.0. Let me know how it works for you!

**Pull request closed without merging**
